### ISSUE TITLE
Request for access

### ISSUE THREAD

**Issue by ni-gergokozma** [jason-fox/fox.jason.passthrough.doxygen#4]
Hello @jason-fox!

Great job with the conversion code!

I'd like to suggest some edits to your plug-in. Could you please provide me access, so I can create a PR? You could then review the edits as you see fit.

Best Regards!

**Comment by jason-fox** [comment]
@ni-gergokozma  you should already be able to [fork this project](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) to create your own GitHub repo of the source code `https://github.comni-gergokozma/fox.jason.passthrough.doxygen` - you would then have full control over your edits.

When you want to create the final pull request, just raise the PR and I can review.

**Comment by ni-gergokozma** [comment]
That works too! Thank you for your reply.
